import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Laptop, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";

export default function AccountSecurity() {
  const { user, loading } = useAuth();
  const sessions = trpc.auth.sessions.useQuery(undefined, { enabled: Boolean(user) });
  const events = trpc.auth.securityEvents.useQuery(undefined, { enabled: Boolean(user) });
  const revoke = trpc.auth.revokeSession.useMutation({ onSuccess: () => { sessions.refetch(); events.refetch(); toast.success("Session revoked"); }, onError: (error) => toast.error(error.message) });
  if (loading) return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] text-sm text-slate-400">Loading security settings…</main>;
  if (!user) return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] px-6 text-center"><div><ShieldCheck className="mx-auto h-7 w-7 text-slate-400" /><h1 className="mt-4 text-2xl font-semibold text-slate-950">Sign in to manage security</h1><Link href="/login"><Button className="mt-5">Sign in</Button></Link></div></main>;
  return <main className="min-h-screen bg-[#f7f7f3] px-5 py-8 md:px-10"><div className="mx-auto max-w-4xl"><Link href="/account" className="text-xs font-medium text-slate-400 hover:text-slate-700">← Your library</Link><header className="mt-8"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">Account controls</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.06em] text-slate-950">Security & sessions</h1><p className="mt-2 text-sm text-slate-500">Review active browser sessions and your recent account activity.</p></header><section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold text-slate-950">Browser sessions</h2></div>{sessions.data?.length ? <div className="divide-y divide-slate-100">{sessions.data.map((session) => <div className="flex flex-wrap items-center gap-4 px-5 py-4" key={session.id}><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-600"><Laptop className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-900">{session.userAgent || "Unknown device"}</p><p className="mt-1 text-xs text-slate-400">{session.ipAddress || "Unknown IP"} · last used {new Date(session.lastUsedAt).toLocaleString()}</p></div><span className="text-xs text-slate-400">{session.revokedAt ? "Revoked" : `Expires ${new Date(session.expiresAt).toLocaleDateString()}`}</span><Button size="sm" variant="outline" disabled={Boolean(session.revokedAt) || revoke.isPending} onClick={() => revoke.mutate({ id: session.id })}>{session.revokedAt ? "Revoked" : "Revoke"}</Button></div>)}</div> : <p className="px-5 py-10 text-center text-sm text-slate-400">No active sessions found.</p>}</section><section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold text-slate-950">Recent security activity</h2></div>{events.data?.length ? <div className="divide-y divide-slate-100">{events.data.map((event) => <div key={event.id} className="px-5 py-4"><p className="text-sm font-medium text-slate-800">{event.action}</p><p className="mt-1 text-xs text-slate-400">{new Date(event.createdAt).toLocaleString()} · {event.ipAddress || "Unknown IP"}</p></div>)}</div> : <p className="px-5 py-10 text-center text-sm text-slate-400">No security events yet.</p>}</section></div></main>;
}
