import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowLeft, ChartNoAxesCombined, DollarSign, ReceiptText, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export default function AdminReports() {
  const { user } = useAuth(); const staff = Boolean(user && ["admin", "super_admin", "support"].includes(user.role)); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const input = useMemo(() => ({ from: from ? new Date(`${from}T00:00:00`) : undefined, to: to ? new Date(`${to}T23:59:59`) : undefined }), [from, to]); const report = trpc.admin.reports.useQuery(input, { enabled: staff }); const enhanced = trpc.admin.enhancedReports.useQuery(input, { enabled: staff });
  if (!staff) return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] px-6 text-center"><div><ChartNoAxesCombined className="mx-auto h-7 w-7 text-slate-400" /><h1 className="mt-4 text-2xl font-semibold text-slate-950">Admin access required</h1><Link href="/admin"><Button variant="outline" className="mt-5"><ArrowLeft className="mr-2 h-4 w-4" />Back to admin</Button></Link></div></main>;
  const metrics = [{ label: "GMV", value: money.format(report.data?.gmv || 0), icon: DollarSign }, { label: "MRR", value: money.format(enhanced.data?.mrr || 0), icon: DollarSign }, { label: "Paid orders", value: report.data?.paidOrders || 0, icon: ReceiptText }, { label: "New accounts", value: report.data?.users || 0, icon: Users }, { label: "Store views", value: report.data?.visits || 0, icon: Activity }, { label: "Managed files", value: enhanced.data?.managedFiles || 0, icon: Activity }];
  return <main className="min-h-screen bg-[#f7f7f3] px-5 py-8 md:px-10"><div className="mx-auto max-w-6xl"><Link href="/admin" className="text-xs font-medium text-slate-400 hover:text-slate-700">← CreaDock Admin</Link><header className="mt-8"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">Platform intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.06em] text-slate-950">Reports</h1><p className="mt-2 text-sm text-slate-500">Filter revenue, growth, subscriptions, refunds, support, and traffic data.</p></header><div className="mt-6 flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-4"><label className="text-xs font-medium text-slate-600">From<Input className="mt-1" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="text-xs font-medium text-slate-600">To<Input className="mt-1" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><Button variant="outline" onClick={() => { setFrom(""); setTo(""); }}>Clear dates</Button></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{metrics.map((metric) => <section key={metric.label} className="rounded-2xl border border-slate-200 bg-white p-5"><metric.icon className="h-4 w-4 text-slate-400" /><p className="mt-5 text-xs text-slate-500">{metric.label}</p><p className="mt-1 text-2xl font-semibold tracking-[-.05em] text-slate-950">{metric.value}</p></section>)}</div><section className="mt-6 grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Active subscriptions</p><p className="mt-1 text-xl font-semibold text-slate-950">{enhanced.data?.activeSubscriptions || 0}</p></div><div><p className="text-xs text-slate-500">Payment events</p><p className="mt-1 text-xl font-semibold text-slate-950">{enhanced.data?.paymentEvents || 0}</p></div><div><p className="text-xs text-slate-500">Open support</p><p className="mt-1 text-xl font-semibold text-slate-950">{report.data?.openSupport || 0}</p></div></section></div></main>;
}
