import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Database, Package, ReceiptText, Store, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

type Tab = "users" | "creators" | "products" | "orders" | "subscriptions" | "payments" | "support";
const labels: Record<Tab, string> = { users: "Users", creators: "Creators", products: "Products", orders: "Orders", subscriptions: "Subscriptions", payments: "Payments", support: "Support" };

export default function AdminOperations() {
  const { user } = useAuth(); const staff = Boolean(user && ["admin", "super_admin", "support"].includes(user.role)); const data = trpc.admin.operations.useQuery(undefined, { enabled: staff }); const [tab, setTab] = useState<Tab>("users");
  const rows = useMemo(() => data.data?.[tab] || [], [data.data, tab]) as Array<Record<string, unknown>>;
  if (!staff) return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] px-6 text-center"><div><Database className="mx-auto h-7 w-7 text-slate-400" /><h1 className="mt-4 text-2xl font-semibold text-slate-950">Admin access required</h1><Link href="/admin"><Button variant="outline" className="mt-5"><ArrowLeft className="mr-2 h-4 w-4" />Back to admin</Button></Link></div></main>;
  return <main className="min-h-screen bg-[#f7f7f3] px-5 py-8 md:px-10"><div className="mx-auto max-w-7xl"><Link href="/admin" className="text-xs font-medium text-slate-400 hover:text-slate-700">← CreaDock Admin</Link><header className="mt-8"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">Platform operations</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.06em] text-slate-950">Operational records</h1><p className="mt-2 text-sm text-slate-500">Browse the latest platform records across commerce, creators, and support.</p></header><div className="mt-7 flex flex-wrap gap-2">{(Object.keys(labels) as Tab[]).map((key) => <Button key={key} size="sm" variant={tab === key ? "default" : "outline"} onClick={() => setTab(key)}>{labels[key]}</Button>)}</div><section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center gap-2 border-b border-slate-100 px-5 py-4"><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-100 text-slate-600">{tab === "users" ? <Users className="h-4 w-4" /> : tab === "creators" ? <Store className="h-4 w-4" /> : tab === "products" ? <Package className="h-4 w-4" /> : <ReceiptText className="h-4 w-4" />}</span><h2 className="text-sm font-semibold text-slate-950">{labels[tab]}</h2><span className="ml-auto text-xs text-slate-400">Latest {rows.length}</span></div>{data.isLoading ? <p className="px-5 py-10 text-center text-sm text-slate-400">Loading records…</p> : rows.length ? <div className="divide-y divide-slate-100">{rows.map((row, index) => <div className="grid grid-cols-[minmax(0,1fr)_auto] gap-4 px-5 py-4" key={String(row.id || index)}><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-900">{String(row.name || row.displayName || row.title || row.orderNumber || row.action || row.subject || row.providerEventId || `Record ${row.id}`)}</p><p className="mt-1 truncate text-xs text-slate-400">{String(row.email || row.handle || row.status || row.type || row.role || "Platform record")}</p></div><p className="text-xs text-slate-400">{row.createdAt ? new Date(String(row.createdAt)).toLocaleString() : ""}</p></div>)}</div> : <p className="px-5 py-10 text-center text-sm text-slate-400">No records are available in this category.</p>}</section></div></main>;
}
