import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, Settings2, TriangleAlert } from "lucide-react";
import { Link } from "wouter";

export default function AdminSettings() {
  const { user } = useAuth(); const staff = Boolean(user && ["admin", "super_admin"].includes(user.role)); const configuration = trpc.admin.configuration.useQuery(undefined, { enabled: staff });
  if (!staff) return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] px-6 text-center"><div><Settings2 className="mx-auto h-7 w-7 text-slate-400" /><h1 className="mt-4 text-2xl font-semibold text-slate-950">Administrator access required</h1><Link href="/admin"><Button variant="outline" className="mt-5"><ArrowLeft className="mr-2 h-4 w-4" />Back to admin</Button></Link></div></main>;
  const stripeReady = Boolean(configuration.data?.stripe.configured); const smtpReady = Boolean(configuration.data?.smtp.configured);
  return <main className="min-h-screen bg-[#f7f7f3] px-5 py-8 md:px-10"><div className="mx-auto max-w-4xl"><Link href="/admin" className="text-xs font-medium text-slate-400 hover:text-slate-700">← CreaDock Admin</Link><header className="mt-8"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">Platform settings</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.06em] text-slate-950">Provider readiness</h1><p className="mt-2 text-sm text-slate-500">Secure server-side configuration required before enabling live commerce and email.</p></header><div className="mt-8 grid gap-5 md:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-6"><span className={`grid h-10 w-10 place-items-center rounded-xl ${stripeReady ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{stripeReady ? <CheckCircle2 className="h-5 w-5" /> : <TriangleAlert className="h-5 w-5" />}</span><h2 className="mt-5 text-lg font-semibold text-slate-950">Stripe payments</h2><p className="mt-2 text-sm leading-6 text-slate-500">{stripeReady ? "API, browser, and webhook credentials are configured." : "Add the Secret Key, Publishable Key, and Webhook Signing Secret in secure project settings."}</p><p className="mt-4 text-xs font-medium text-slate-400">Status: {stripeReady ? "Ready" : "Action required"}</p></section><section className="rounded-2xl border border-slate-200 bg-white p-6"><span className={`grid h-10 w-10 place-items-center rounded-xl ${smtpReady ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{smtpReady ? <CheckCircle2 className="h-5 w-5" /> : <TriangleAlert className="h-5 w-5" />}</span><h2 className="mt-5 text-lg font-semibold text-slate-950">SMTP delivery</h2><p className="mt-2 text-sm leading-6 text-slate-500">{smtpReady ? `Sender ${configuration.data?.smtp.from || "configured"} is ready for transactional delivery.` : "Add SMTP host, port, username, password, and verified sender identity in secure project settings."}</p><p className="mt-4 text-xs font-medium text-slate-400">Status: {smtpReady ? "Ready" : "Action required"}</p></section></div><p className="mt-6 text-xs leading-5 text-slate-400">Credentials are intentionally not editable in the browser. Use secure project settings to protect payment and email secrets.</p></div></main>;
}
