import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowLeft, CircleAlert, LifeBuoy, Mail, Search, ShieldCheck, Store, Users } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { toast } from "sonner";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const staffRoles = ["admin", "super_admin", "support"];

export default function AdminPanel() {
  const { user } = useAuth();
  const staff = Boolean(user && staffRoles.includes(user.role));
  const [query, setQuery] = useState("");
  const summary = trpc.admin.overview.useQuery(undefined, { enabled: staff });
  const tickets = trpc.admin.tickets.useQuery(undefined, { enabled: staff });
  const configuration = trpc.admin.configuration.useQuery(undefined, { enabled: staff && user?.role !== "support" });
  const userList = trpc.admin.users.useQuery({ query: query || undefined }, { enabled: staff && user?.role !== "support" });
  const updateTicket = trpc.admin.updateTicket.useMutation({ onSuccess: () => tickets.refetch() });
  const updateUser = trpc.admin.updateUserStatus.useMutation({ onSuccess: () => { userList.refetch(); toast.success("Account status updated"); }, onError: (error) => toast.error(error.message) });
  if (!user || !staff) return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] px-6 text-center"><div><span className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-slate-950 text-white"><ShieldCheck className="h-5 w-5" /></span><h1 className="mt-5 text-3xl font-semibold tracking-[-.06em] text-slate-950">Admin access required</h1><p className="mt-3 text-sm text-slate-500">This area is reserved for CreaDock platform administrators and support staff.</p><Link href="/app/dashboard"><Button variant="outline" className="mt-6"><ArrowLeft className="mr-2 h-4 w-4" />Back to workspace</Button></Link></div></main>;
  return <main className="min-h-screen bg-[#f7f7f3] px-5 py-8 md:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">Platform operations</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.06em] text-slate-950">CreaDock Admin</h1><p className="mt-2 text-sm text-slate-500">Monitor account health, payments, provider readiness, and support.</p></div><Link href="/app/dashboard"><Button variant="outline">Creator workspace</Button></Link></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Creators", value: summary.data?.creators ?? 0, icon: Users }, { label: "Platform GMV", value: money.format(summary.data?.platformRevenue ?? 0), icon: Activity }, { label: "Paid orders", value: summary.data?.paidOrders ?? 0, icon: Store }, { label: "Open support", value: summary.data?.openTickets ?? 0, icon: LifeBuoy }].map((metric) => <section key={metric.label} className="rounded-2xl border border-slate-200 bg-white p-5"><metric.icon className="h-4 w-4 text-slate-400" /><p className="mt-5 text-xs text-slate-500">{metric.label}</p><p className="mt-1 text-2xl font-semibold tracking-[-.05em] text-slate-950">{metric.value}</p></section>)}</div>
    {user?.role !== "support" ? <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold text-slate-950">Provider readiness</h2><p className="mt-1 text-xs text-slate-500">Secrets are configured through secure project settings, never stored in browser forms.</p></div><Badge variant="outline" className="border-slate-200 text-slate-600">Production configuration</Badge></div><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-medium text-slate-900"><CircleAlert className="h-4 w-4 text-slate-500" />Stripe payments</span><Badge className={configuration.data?.stripe.configured ? "bg-emerald-50 text-emerald-700 hover:bg-emerald-50" : "bg-amber-50 text-amber-700 hover:bg-amber-50"}>{configuration.data?.stripe.configured ? "Ready" : "Needs keys"}</Badge></div><p className="mt-3 text-xs leading-5 text-slate-500">{configuration.data?.stripe.configured ? "Checkout and verified webhooks are configured." : "Add Stripe secret, publishable, and webhook keys in project payment settings."}</p></div><div className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-medium text-slate-900"><Mail className="h-4 w-4 text-slate-500" />SMTP email</span><Badge className={configuration.data?.smtp.configured ? "bg-emerald-50 text-emerald-700 hover:bg-emerald-50" : "bg-amber-50 text-amber-700 hover:bg-amber-50"}>{configuration.data?.smtp.configured ? "Ready" : "Needs settings"}</Badge></div><p className="mt-3 text-xs leading-5 text-slate-500">{configuration.data?.smtp.configured ? `Sending from ${configuration.data.smtp.from}.` : "Add SMTP host, port, username, password, and sender address in secure project settings."}</p></div></div></section> : null}
    {user?.role !== "support" ? <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><h2 className="text-sm font-semibold text-slate-950">User accounts</h2><p className="mt-1 text-xs text-slate-400">Search, verify status, and suspend accounts when necessary.</p></div><div className="relative w-full sm:w-64"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search accounts" /></div></div>{userList.data?.length ? <div className="divide-y divide-slate-100">{userList.data.map((account) => <div className="flex flex-wrap items-center gap-3 px-5 py-4" key={account.id}><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-800">{account.name || account.username || "Unnamed account"}</p><p className="truncate text-xs text-slate-400">{account.email || "No email"} · {account.role}</p></div><Badge variant="outline" className="border-slate-200 text-slate-600">{account.emailVerifiedAt ? "Verified" : "Unverified"}</Badge><Badge className={account.accountStatus === "active" ? "bg-emerald-50 text-emerald-700 hover:bg-emerald-50" : account.accountStatus === "suspended" ? "bg-rose-50 text-rose-700 hover:bg-rose-50" : "bg-amber-50 text-amber-700 hover:bg-amber-50"}>{account.accountStatus}</Badge><Button size="sm" variant="outline" disabled={updateUser.isPending || account.id === user.id} onClick={() => updateUser.mutate({ id: account.id, accountStatus: account.accountStatus === "suspended" ? "active" : "suspended" })}>{account.accountStatus === "suspended" ? "Restore" : "Suspend"}</Button></div>)}</div> : <div className="px-5 py-10 text-center text-sm text-slate-400">No matching accounts.</div>}</section> : null}
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold text-slate-950">Recent creators</h2></div>{summary.data?.recentCreators?.length ? <div className="divide-y divide-slate-100">{summary.data.recentCreators.map((creator) => <div className="flex items-center gap-3 px-5 py-4" key={creator.id}><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-100 text-xs font-semibold text-slate-600">{creator.displayName.slice(0, 1)}</span><div className="flex-1"><p className="text-sm font-medium text-slate-800">{creator.displayName}</p><p className="text-xs text-slate-400">/c/{creator.handle}</p></div><Badge className={creator.isPublished ? "bg-emerald-50 text-emerald-700 hover:bg-emerald-50" : "bg-slate-100 text-slate-600 hover:bg-slate-100"}>{creator.isPublished ? "Published" : "Draft"}</Badge></div>)}</div> : <div className="px-5 py-12 text-center text-sm text-slate-400">Creators will appear here as accounts are created.</div>}</section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold text-slate-950">Support queue</h2></div>{tickets.data?.length ? <div className="divide-y divide-slate-100">{tickets.data.map((ticket) => <div className="flex items-center gap-3 px-5 py-4" key={ticket.id}><div className="flex-1"><p className="text-sm font-medium text-slate-800">{ticket.subject}</p><p className="mt-1 text-xs text-slate-400">{ticket.priority} priority</p></div><Button size="sm" variant="outline" disabled={ticket.status === "resolved" || updateTicket.isPending} onClick={() => updateTicket.mutate({ id: ticket.id, status: "resolved" })}>{ticket.status === "resolved" ? "Resolved" : "Resolve"}</Button></div>)}</div> : <div className="px-5 py-12 text-center text-sm text-slate-400">The support queue is clear.</div>}</section></div></div></main>;
}
