import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, KeyRound, Loader2, Mail, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";

function AuthShell({ children, title, subtitle }: { children: React.ReactNode; title: string; subtitle: string }) {
  return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] px-5 py-10"><section className="w-full max-w-md"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-950"><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-950 text-xs text-white">C</span>CreaDock</Link><div className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_24px_60px_-42px_rgba(15,23,42,.35)] sm:p-8"><h1 className="text-3xl font-semibold tracking-[-.06em] text-slate-950">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{subtitle}</p>{children}</div></section></main>;
}

export default function AuthPage() {
  const [location, setLocation] = useLocation();
  const query = new URLSearchParams(location.split("?")[1] || "");
  const token = query.get("token") || "";
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [remember, setRemember] = useState(true);
  const signUp = trpc.auth.signUp.useMutation({ onSuccess: () => { toast.success("Account created. Check your email to verify it."); setLocation("/login"); }, onError: (error) => toast.error(error.message) });
  const login = trpc.auth.login.useMutation({ onSuccess: () => { toast.success("Welcome back"); setLocation("/app"); }, onError: (error) => toast.error(error.message) });
  const requestReset = trpc.auth.requestPasswordReset.useMutation({ onSuccess: (result) => toast.success(result.message), onError: (error) => toast.error(error.message) });
  const reset = trpc.auth.resetPassword.useMutation({ onSuccess: () => { toast.success("Password updated. Please sign in."); setLocation("/login"); }, onError: (error) => toast.error(error.message) });
  const verify = trpc.auth.verifyEmail.useMutation({ onSuccess: () => { toast.success("Email verified. Your account is ready."); setLocation("/app"); }, onError: (error) => toast.error(error.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); if (location.startsWith("/signup")) signUp.mutate({ name, email, username, password, confirmPassword }); else if (location.startsWith("/login")) login.mutate({ email, password, remember }); else if (location.startsWith("/forgot-password")) requestReset.mutate({ email }); else if (location.startsWith("/reset-password")) reset.mutate({ token, password, confirmPassword }); };
  if (location.startsWith("/verify-email")) return <AuthShell title="Verify your account" subtitle="Confirm your email address to activate your CreaDock account."><div className="mt-7"><Button className="w-full bg-slate-950 text-white" disabled={!token || verify.isPending} onClick={() => verify.mutate({ token })}>{verify.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ShieldCheck className="mr-2 h-4 w-4" />}Verify email</Button><p className="mt-4 text-center text-xs text-slate-400">Verification links expire for your security.</p></div></AuthShell>;
  const isSignup = location.startsWith("/signup"); const isForgot = location.startsWith("/forgot-password"); const isReset = location.startsWith("/reset-password");
  const title = isSignup ? "Create your account" : isForgot ? "Reset your password" : isReset ? "Choose a new password" : "Welcome back";
  const subtitle = isSignup ? "Start building a storefront, products, and an audience in one place." : isForgot ? "Enter your account email and we will send a secure reset link." : isReset ? "Use a strong, unique password for your CreaDock account." : "Sign in to manage your creator business.";
  const pending = signUp.isPending || login.isPending || requestReset.isPending || reset.isPending;
  return <AuthShell title={title} subtitle={subtitle}><form className="mt-7 space-y-4" onSubmit={submit}>{isSignup ? <><div className="space-y-2"><Label>Full name</Label><Input value={name} onChange={(event) => setName(event.target.value)} required placeholder="Your name" /></div><div className="space-y-2"><Label>Username</Label><Input value={username} onChange={(event) => setUsername(event.target.value.toLowerCase().replace(/[^a-z0-9_-]/g, ""))} required placeholder="your-name" /></div></> : null}{!isReset ? <div className="space-y-2"><Label>Email</Label><Input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required placeholder="you@example.com" /></div> : null}{!isForgot ? <><div className="space-y-2"><Label>Password</Label><Input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required minLength={12} placeholder="At least 12 characters" /></div>{(isSignup || isReset) ? <div className="space-y-2"><Label>Confirm password</Label><Input type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required minLength={12} placeholder="Confirm your password" /></div> : null}</> : null}{!isSignup && !isForgot && !isReset ? <label className="flex cursor-pointer items-center gap-2 text-sm text-slate-500"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} />Keep me signed in</label> : null}<Button type="submit" className="w-full bg-slate-950 text-white hover:bg-slate-800" disabled={pending}>{pending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : isForgot ? <Mail className="mr-2 h-4 w-4" /> : isReset ? <KeyRound className="mr-2 h-4 w-4" /> : isSignup ? <CheckCircle2 className="mr-2 h-4 w-4" /> : null}{isSignup ? "Create account" : isForgot ? "Request reset link" : isReset ? "Update password" : "Sign in"}</Button></form><div className="mt-6 text-center text-sm text-slate-500">{isSignup ? <>Already have an account? <Link href="/login" className="font-medium text-slate-950">Sign in</Link></> : isForgot || isReset ? <Link href="/login" className="font-medium text-slate-950">Back to sign in</Link> : <>New to CreaDock? <Link href="/signup" className="font-medium text-slate-950">Create an account</Link><br /><Link href="/forgot-password" className="mt-2 inline-block text-xs font-medium text-slate-600">Forgot your password?</Link></>}</div></AuthShell>;
}
