import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BellRing, LockKeyhole, MessageCircle, Plus, Send, ShieldCheck, Trash2, Users } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const field = "h-10 border-slate-200 bg-white text-sm focus-visible:ring-slate-950";
function Panel({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-200 bg-white ${className}`}>{children}</section>; }

export default function CommunityStudio() {
  const spaces = trpc.community.spaces.useQuery();
  const plans = trpc.memberships.list.useQuery();
  const products = trpc.products.list.useQuery();
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const members = trpc.community.members.useQuery({ communityId: selectedId ?? 0 }, { enabled: Boolean(selectedId) });
  const posts = trpc.community.posts.useQuery({ communityId: selectedId ?? 0 }, { enabled: Boolean(selectedId) });
  const [editorOpen, setEditorOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [accessType, setAccessType] = useState<"public" | "members" | "product">("members");
  const [membershipPlanId, setMembershipPlanId] = useState("none");
  const [productId, setProductId] = useState("none");
  const [published, setPublished] = useState(false);
  const [announcementTitle, setAnnouncementTitle] = useState("");
  const [announcementBody, setAnnouncementBody] = useState("");
  const utils = trpc.useUtils();
  const save = trpc.community.saveSpace.useMutation({ onSuccess: (id) => { toast.success("Community space saved"); spaces.refetch(); setSelectedId(id); closeEditor(); } });
  const remove = trpc.community.removeSpace.useMutation({ onSuccess: () => { toast.success("Community space removed"); spaces.refetch(); setSelectedId(null); } });
  const announcement = trpc.community.createAnnouncement.useMutation({ onSuccess: () => { toast.success("Announcement posted"); posts.refetch(); setAnnouncementTitle(""); setAnnouncementBody(""); } });
  const moderate = trpc.community.moderatePost.useMutation({ onSuccess: () => posts.refetch() });
  const updateMember = trpc.community.updateMember.useMutation({ onSuccess: () => { toast.success("Member updated"); members.refetch(); } });
  const selected = spaces.data?.find((space) => space.id === selectedId);

  function closeEditor() { setEditorOpen(false); setEditingId(null); setName(""); setDescription(""); setAccessType("members"); setMembershipPlanId("none"); setProductId("none"); setPublished(false); }
  function edit(space?: NonNullable<typeof spaces.data>[number]) { if (space) { setEditingId(space.id); setName(space.name); setDescription(space.description || ""); setAccessType(space.accessType); setMembershipPlanId(space.membershipPlanId ? String(space.membershipPlanId) : "none"); setProductId(space.productId ? String(space.productId) : "none"); setPublished(space.isPublished); } else closeEditor(); setEditorOpen(true); }
  function saveSpace() { if (!name.trim()) return; if (accessType === "members" && membershipPlanId === "none") return toast.error("Choose the membership plan that grants access."); if (accessType === "product" && productId === "none") return toast.error("Choose the product that grants access."); save.mutate({ id: editingId ?? undefined, name: name.trim(), description: description || undefined, accessType, membershipPlanId: accessType === "members" ? Number(membershipPlanId) : null, productId: accessType === "product" ? Number(productId) : null, isPublished: published }); }

  if (spaces.error) return <Panel className="grid min-h-72 place-items-center p-8 text-center text-sm text-slate-500">Community spaces could not be loaded. Refresh the workspace and try again.</Panel>;
  return <><header className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">Member experience</p><h1 className="mt-2 text-[30px] font-semibold tracking-[-.055em] text-slate-950 md:text-[34px]">Community</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Create intentional spaces for conversations, member updates, and light-touch support—without recreating a chat server.</p></div><Button className="h-10 bg-slate-950 text-white hover:bg-slate-800" onClick={() => edit()}><Plus className="mr-2 h-4 w-4" />New space</Button></header>
    {editorOpen ? <Panel className="mb-6 p-5 md:p-6"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-900">{editingId ? "Edit community space" : "Create community space"}</p><p className="mt-1 text-xs text-slate-400">Set the access rule first, then publish when the space is ready for people.</p></div><Button size="sm" variant="outline" onClick={closeEditor}>Close</Button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><Label>Space name</Label><Input className={`mt-2 ${field}`} value={name} onChange={(event) => setName(event.target.value)} placeholder="Creator Pro Community" /></div><div><Label>Access rule</Label><select className={`mt-2 w-full rounded-md px-3 ${field}`} value={accessType} onChange={(event) => setAccessType(event.target.value as typeof accessType)}><option value="public">Public</option><option value="members">Membership required</option><option value="product">Product purchase required</option></select></div><div className="md:col-span-2"><Label>Description</Label><Textarea className="mt-2 min-h-20 border-slate-200 bg-white" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Who this space is for and what members can expect." /></div>{accessType === "members" ? <div><Label>Membership plan</Label><select className={`mt-2 w-full rounded-md px-3 ${field}`} value={membershipPlanId} onChange={(event) => setMembershipPlanId(event.target.value)}><option value="none">Choose a plan</option>{plans.data?.map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></div> : null}{accessType === "product" ? <div><Label>Eligible product</Label><select className={`mt-2 w-full rounded-md px-3 ${field}`} value={productId} onChange={(event) => setProductId(event.target.value)}><option value="none">Choose a product</option>{products.data?.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></div> : null}<label className="flex items-center gap-2 self-end pb-2 text-sm text-slate-600"><input type="checkbox" checked={published} onChange={(event) => setPublished(event.target.checked)} className="h-4 w-4 rounded border-slate-300" />Publish this space</label></div><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={closeEditor}>Cancel</Button><Button disabled={save.isPending || !name.trim()} onClick={saveSpace}>{editingId ? "Save space" : "Create space"}</Button></div></Panel> : null}
    <div className="grid gap-6 xl:grid-cols-[290px_minmax(0,1fr)]"><Panel className="h-fit overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><p className="text-sm font-semibold text-slate-900">Your spaces</p></div><div className="divide-y divide-slate-100">{spaces.data?.length ? spaces.data.map((space) => <button key={space.id} onClick={() => setSelectedId(space.id)} className={`w-full px-5 py-4 text-left ${space.id === selectedId ? "bg-slate-50" : "hover:bg-slate-50"}`}><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-medium text-slate-800">{space.name}</p><Badge variant="secondary" className="bg-slate-100 text-[10px] text-slate-500">{space.accessType}</Badge></div><p className="mt-1 text-xs text-slate-400">{space.isPublished ? "Published" : "Draft"}</p></button>) : <p className="p-5 text-sm text-slate-400">Create your first space to invite people in.</p>}</div></Panel>
      {selected ? <div className="space-y-6"><Panel className="p-5 md:p-6"><div className="flex flex-col gap-4 border-b border-slate-100 pb-5 md:flex-row md:items-start md:justify-between"><div><div className="flex items-center gap-2"><MessageCircle className="h-4 w-4 text-slate-500" /><p className="text-sm font-semibold text-slate-900">{selected.name}</p></div><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">{selected.description || "No description yet."}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => edit(selected)}>Edit</Button><Button size="icon" variant="ghost" className="h-8 w-8 text-red-600" onClick={() => remove.mutate({ id: selected.id })}><Trash2 className="h-3.5 w-3.5" /></Button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Access</p><p className="mt-2 text-sm font-semibold text-slate-800">{selected.accessType === "members" ? "Membership" : selected.accessType === "product" ? "Product" : "Public"}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Members</p><p className="mt-2 text-sm font-semibold text-slate-800">{members.data?.length ?? 0}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Status</p><p className="mt-2 text-sm font-semibold text-slate-800">{selected.isPublished ? "Published" : "Draft"}</p></div></div></Panel>
        <Panel className="p-5 md:p-6"><div className="flex items-center gap-2"><BellRing className="h-4 w-4 text-slate-500" /><p className="text-sm font-semibold text-slate-900">Post an announcement</p></div><div className="mt-4 grid gap-3"><Input className={field} value={announcementTitle} onChange={(event) => setAnnouncementTitle(event.target.value)} placeholder="A clear update for members" /><Textarea className="min-h-24 border-slate-200 bg-white" value={announcementBody} onChange={(event) => setAnnouncementBody(event.target.value)} placeholder="Share the context, next step, or useful resource." /></div><div className="mt-4 flex justify-end"><Button disabled={!announcementTitle.trim() || !announcementBody.trim() || announcement.isPending} onClick={() => announcement.mutate({ communityId: selected.id, title: announcementTitle.trim(), body: announcementBody.trim() })}><Send className="mr-2 h-4 w-4" />Post announcement</Button></div></Panel>
        <div className="grid gap-6 lg:grid-cols-2"><Panel className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><p className="text-sm font-semibold text-slate-900">Member list</p></div>{members.data?.length ? <div className="divide-y divide-slate-100">{members.data.map((entry) => <div key={entry.communityMembers.id} className="flex items-center gap-3 px-5 py-4"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-100"><Users className="h-3.5 w-3.5 text-slate-500" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-800">{entry.customers.name || entry.customers.email}</p><p className="text-xs text-slate-400">{entry.communityMembers.role}</p></div><select className="h-8 rounded-md border border-slate-200 bg-white px-2 text-xs" value={entry.communityMembers.status} onChange={(event) => updateMember.mutate({ communityId: selected.id, customerId: entry.customers.id, status: event.target.value as "active" | "removed" })}><option value="active">Active</option><option value="removed">Removed</option></select></div>)}</div> : <p className="px-5 py-10 text-center text-sm text-slate-400">Eligible people can join when the space is live.</p>}</Panel><Panel className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><p className="text-sm font-semibold text-slate-900">Recent posts</p></div>{posts.data?.length ? <div className="divide-y divide-slate-100">{posts.data.map((post) => <div key={post.id} className="px-5 py-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-4 w-4 text-slate-400" /><div className="min-w-0 flex-1"><p className="text-sm font-medium text-slate-800">{post.title || "Member post"}</p><p className="mt-1 line-clamp-3 text-xs leading-5 text-slate-500">{post.body}</p></div><Button size="sm" variant="ghost" className="h-8 px-2" onClick={() => moderate.mutate({ id: post.id, communityId: selected.id, status: post.status === "hidden" ? "published" : "hidden" })}>{post.status === "hidden" ? "Restore" : "Hide"}</Button></div></div>)}</div> : <p className="px-5 py-10 text-center text-sm text-slate-400">Announcements and member posts will appear here.</p>}</Panel></div></div> : <Panel className="grid min-h-80 place-items-center p-8 text-center"><div><LockKeyhole className="mx-auto h-7 w-7 text-slate-300" /><p className="mt-4 text-sm font-medium text-slate-700">Select a community space</p><p className="mt-2 max-w-sm text-sm leading-6 text-slate-400">Set an access rule, publish it, then manage the conversations and members from this workspace.</p></div></Panel>}</div></>;
}
