import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Download, LogIn, PackageCheck, ShoppingBag } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });

export default function CustomerPortal() {
  const { user, loading } = useAuth();
  const purchases = trpc.account.purchases.useQuery(undefined, { enabled: Boolean(user) });
  const learning = trpc.account.learning.useQuery(undefined, { enabled: Boolean(user) });
  const bookings = trpc.account.bookings.useQuery(undefined, { enabled: Boolean(user) });
  const memberships = trpc.account.memberships.useQuery(undefined, { enabled: Boolean(user) });
  const [productId, setProductId] = useState<number | null>(null);
  const download = trpc.account.download.useQuery({ productId: productId ?? 0 }, { enabled: productId !== null, retry: false });
  useEffect(() => { if (download.data?.url) { window.open(download.data.url, "_blank", "noopener,noreferrer"); setProductId(null); } if (download.error) { toast.error(download.error.message); setProductId(null); } }, [download.data?.url, download.error]);
  if (loading) return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] text-sm text-slate-400">Loading account…</main>;
  if (!user) return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] px-6 text-center"><div><span className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-slate-950 text-white"><ShoppingBag className="h-5 w-5" /></span><h1 className="mt-5 text-3xl font-semibold tracking-[-.06em] text-slate-950">Your purchases, in one place</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-slate-500">Sign in with the email you used when you purchased to access products, courses, bookings, and memberships.</p><Link href="/login"><Button className="mt-6 bg-slate-950 text-white"><LogIn className="mr-2 h-4 w-4" />Sign in</Button></Link></div></main>;
  return <main className="min-h-screen bg-[#f7f7f3] px-5 py-8 md:px-10"><div className="mx-auto max-w-4xl"><Link href="/" className="text-xs font-medium text-slate-400 hover:text-slate-700">← CreaDock</Link><header className="mt-8"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">Customer account</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.06em] text-slate-950">Your library</h1><p className="mt-2 text-sm text-slate-500">Purchases and protected digital access for {user.email}.</p><Link href="/account/security"><Button variant="outline" size="sm" className="mt-4">Security & sessions</Button></Link></header>
    {purchases.isLoading ? <p className="mt-10 text-sm text-slate-400">Loading purchases…</p> : purchases.error ? <section className="mt-8 rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-800">We could not load your library. <Button variant="link" className="h-auto p-0 text-rose-800" onClick={() => purchases.refetch()}>Try again</Button></section> : purchases.data?.length ? <section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold text-slate-950">Purchase history</h2></div><div className="divide-y divide-slate-100">{purchases.data.map((row) => <div key={`${row.orders.id}-${row.orderItems.id}`} className="flex flex-wrap items-center gap-4 px-5 py-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><PackageCheck className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-900">{row.orderItems.title}</p><p className="mt-1 text-xs text-slate-400">Order {row.orders.orderNumber} · {new Date(row.orders.createdAt).toLocaleDateString()}</p></div><p className="text-sm font-medium text-slate-700">{money.format(Number(row.orderItems.unitPrice))}</p>{row.orderItems.productId ? <Button size="sm" variant="outline" disabled={download.isFetching && productId === row.orderItems.productId} onClick={() => setProductId(row.orderItems.productId)}><Download className="mr-2 h-3.5 w-3.5" />Download</Button> : <span className="text-xs text-slate-400">Membership access</span>}</div>)}</div></section> : <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-10 text-center"><ShoppingBag className="mx-auto h-6 w-6 text-slate-300" /><h2 className="mt-4 text-lg font-semibold text-slate-900">No purchases yet</h2><p className="mt-2 text-sm text-slate-500">When you buy from a CreaDock creator, your access will appear here.</p></section>}
    <div className="mt-6 grid gap-5 md:grid-cols-3"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-900">Courses</h2>{learning.data?.length ? <div className="mt-3 space-y-4">{learning.data.map((row) => <div key={row.enrollments.id}><p className="text-sm font-medium text-slate-800">{row.courses.title}</p><p className="mt-1 text-xs text-slate-400">{(row.enrollments.completedLessonIds || []).length} lessons completed</p><Link href={`/account/course/${row.courses.id}`}><Button variant="outline" size="sm" className="mt-3">Open course</Button></Link></div>)}</div> : <p className="mt-3 text-xs text-slate-400">No active course enrollments.</p>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-900">Bookings</h2>{bookings.data?.length ? <div className="mt-3 space-y-3">{bookings.data.map((row) => <div key={row.appointments.id}><p className="text-sm font-medium text-slate-800">{row.services.name}</p><p className="mt-1 text-xs text-slate-400">{row.appointments.status}</p></div>)}</div> : <p className="mt-3 text-xs text-slate-400">No upcoming bookings.</p>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-900">Memberships</h2>{memberships.data?.length ? <div className="mt-3 space-y-3">{memberships.data.map((row) => <div key={row.subscriptions.id}><p className="text-sm font-medium text-slate-800">{row.membershipPlans.name}</p><p className="mt-1 text-xs text-slate-400">{row.subscriptions.status}</p></div>)}</div> : <p className="mt-3 text-xs text-slate-400">No active memberships.</p>}</section></div></div></main>;
}
