import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, LockKeyhole } from "lucide-react";
import { Link, useRoute } from "wouter";
import { toast } from "sonner";

export default function CustomerCourse() {
  const [, params] = useRoute("/account/course/:id"); const courseId = Number(params?.id || 0); const { user } = useAuth();
  const course = trpc.account.course.useQuery({ courseId }, { enabled: Boolean(user && courseId) });
  const complete = trpc.account.completeLesson.useMutation({ onSuccess: () => { course.refetch(); toast.success("Lesson marked complete"); }, onError: (error) => toast.error(error.message) });
  if (!user) return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] px-6 text-center"><div><LockKeyhole className="mx-auto h-7 w-7 text-slate-400" /><h1 className="mt-4 text-2xl font-semibold text-slate-950">Sign in to continue learning</h1><Link href="/login"><Button className="mt-5">Sign in</Button></Link></div></main>;
  if (course.isLoading) return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] text-sm text-slate-400">Loading course…</main>;
  if (course.error || !course.data) return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] px-6 text-center"><div><LockKeyhole className="mx-auto h-7 w-7 text-slate-400" /><h1 className="mt-4 text-2xl font-semibold text-slate-950">Course access unavailable</h1><p className="mt-2 text-sm text-slate-500">This course is available only to enrolled accounts.</p><Link href="/account"><Button variant="outline" className="mt-5">Back to library</Button></Link></div></main>;
  const completed = course.data.enrollment.completedLessonIds || [];
  return <main className="min-h-screen bg-[#f7f7f3] px-5 py-8 md:px-10"><div className="mx-auto max-w-3xl"><Link href="/account" className="text-xs font-medium text-slate-400 hover:text-slate-700">← Your library</Link><header className="mt-8"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">Enrolled course</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.06em] text-slate-950">{course.data.course.title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{course.data.course.description || "Work through each lesson at your own pace."}</p></header><section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold text-slate-950">Lessons</h2></div>{course.data.lessons.map((lesson, index) => <article className="border-b border-slate-100 px-5 py-5 last:border-0" key={lesson.id}><div className="flex gap-3"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full text-xs font-semibold ${completed.includes(lesson.id) ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{completed.includes(lesson.id) ? <CheckCircle2 className="h-4 w-4" /> : index + 1}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-900">{lesson.title}</p><p className="mt-1 text-xs uppercase tracking-[.12em] text-slate-400">{lesson.kind}</p>{lesson.body ? <p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-600">{lesson.body}</p> : null}{lesson.videoUrl ? <a className="mt-3 inline-block text-sm font-medium text-slate-900 underline" href={lesson.videoUrl} target="_blank" rel="noreferrer">Open lesson video</a> : null}<Button className="mt-4" size="sm" variant="outline" disabled={completed.includes(lesson.id) || complete.isPending} onClick={() => complete.mutate({ courseId, lessonId: lesson.id })}>{completed.includes(lesson.id) ? "Completed" : "Mark complete"}</Button></div></div></article>)}</section></div></main>;
}
